#$FreeBSD: head/sys/modules/i2c/controllers/ismt/Makefile 266474 2014-05-20 19:55:06Z jimharris $

.PATH:		${.CURDIR}/../../../../dev/ismt
KMOD		= ismt
SRCS		= device_if.h bus_if.h iicbb_if.h pci_if.h smbus_if.h \
		  ismt.c

.include <bsd.kmod.mk>
