# $FreeBSD: head/sys/modules/i2c/smbus/Makefile 93023 2002-03-23 15:49:15Z nsouch $

.PATH:		${.CURDIR}/../../../dev/isl
KMOD		= isl
SRCS		= isl.c device_if.h bus_if.h smbus_if.h vnode_if.h

.include <bsd.kmod.mk>
